apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams-subscription
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: amq-streams
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
