apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: foo-editors
  namespace: project-foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: User
    name: foo
    namespace: project-foo