apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-bar
bases:
- ../../base

patches:
- target:
    kind: Namespace
    name: for-replacement
  patch: |-
    - op: replace
      path: /metadata/name
      value: project-bar
- target:
    kind: ResourceQuota
    name: resource-quota-memory-cpu
  patch: |-
    - op: replace
      path: /spec/hard/memory
      value: 1Gi