apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-config

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

secretGenerator:
- name: matrix-login-template
  options:
    disableNameSuffixHash: true
  files:
    - login-template/login.html

patchesStrategicMerge:
  - merge-matrix-login-template.yaml