apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: 'kafka-cluster/resources'
    repoURL: 'https://github.com/evanshortiss/rht-summit-2023-gitops-cluster-mgmt'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 1m0s
        factor: 2
