apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-customisations
spec:
  destination:
    name: ''
    namespace: ''
    server: {{ .Values.spec.destination.server }}
  source:
    path: console-customisations
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true