apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-namespaces
spec:
  destination:
    name: ''
    namespace: ''
    server: {{ .Values.spec.destination.server }}
  source:
    path: managed-namespaces/overlays
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true