apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Managed Namespaces
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: namespaces
    repoURL: 'git@github.com:evanshortiss/rht-summit-2023-gitops-cluster-mgmt.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
