apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-memory-cpu
  namespace: for-replacement
  annotations:
    # Ensures that this resource will be applied after the namespace
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    cpu: "2"
    memory: 2Gi
  scopes:
  - NotTerminating